-- Baseline: primary key / unique / check constraints
-- Consolidated from schema-recon reconstruction, verified applied against vbxlpxhvojlaisxcipyh

ALTER TABLE public.activity_logs ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_generations ADD CONSTRAINT valid_status CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])));
ALTER TABLE public.ai_generations ADD CONSTRAINT valid_type CHECK ((generation_type = ANY (ARRAY['image'::text, 'video'::text, 'ad_creative'::text])));
ALTER TABLE public.ai_generations ADD CONSTRAINT ai_generations_pkey PRIMARY KEY (id);
ALTER TABLE public.attendance_logs ADD CONSTRAINT attendance_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.autopilot_actions ADD CONSTRAINT autopilot_actions_pkey PRIMARY KEY (id);
ALTER TABLE public.bulk_email_campaigns ADD CONSTRAINT bulk_email_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.bulk_email_recipients ADD CONSTRAINT bulk_email_recipients_pkey PRIMARY KEY (id);
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id);
ALTER TABLE public.cold_caller_usage ADD CONSTRAINT cold_caller_usage_pkey PRIMARY KEY (id);
ALTER TABLE public.companies ADD CONSTRAINT companies_pkey PRIMARY KEY (id);
ALTER TABLE public.companies ADD CONSTRAINT companies_activation_code_key UNIQUE (activation_code);
ALTER TABLE public.consent_logs ADD CONSTRAINT consent_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.contact_submissions ADD CONSTRAINT contact_submissions_pkey PRIMARY KEY (id);
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE public.cvr_companies ADD CONSTRAINT cvr_companies_pkey PRIMARY KEY (id);
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.deals ADD CONSTRAINT deals_pkey PRIMARY KEY (id);
ALTER TABLE public.email_accounts ADD CONSTRAINT email_accounts_pkey PRIMARY KEY (id);
ALTER TABLE public.email_accounts ADD CONSTRAINT email_accounts_user_id_provider_email_address_key UNIQUE (user_id, provider, email_address);
ALTER TABLE public.email_send_log ADD CONSTRAINT email_send_log_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'suppressed'::text, 'failed'::text, 'bounced'::text, 'complained'::text, 'dlq'::text])));
ALTER TABLE public.email_send_log ADD CONSTRAINT email_send_log_pkey PRIMARY KEY (id);
ALTER TABLE public.email_send_state ADD CONSTRAINT email_send_state_id_check CHECK ((id = 1));
ALTER TABLE public.email_send_state ADD CONSTRAINT email_send_state_pkey PRIMARY KEY (id);
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.email_unsubscribe_tokens ADD CONSTRAINT email_unsubscribe_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.email_unsubscribe_tokens ADD CONSTRAINT email_unsubscribe_tokens_email_key UNIQUE (email);
ALTER TABLE public.email_unsubscribe_tokens ADD CONSTRAINT email_unsubscribe_tokens_token_key UNIQUE (token);
ALTER TABLE public.emails ADD CONSTRAINT emails_pkey PRIMARY KEY (id);
ALTER TABLE public.emails ADD CONSTRAINT emails_email_account_id_gmail_id_key UNIQUE (email_account_id, gmail_id);
ALTER TABLE public.employee_profiles ADD CONSTRAINT employee_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.employee_profiles ADD CONSTRAINT employee_profiles_employee_id_key UNIQUE (employee_id);
ALTER TABLE public.event_subscriptions ADD CONSTRAINT event_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.icp_profiles ADD CONSTRAINT icp_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.icp_search_jobs ADD CONSTRAINT icp_search_jobs_pkey PRIMARY KEY (id);
ALTER TABLE public.integrations ADD CONSTRAINT integrations_pkey PRIMARY KEY (id);
ALTER TABLE public.integrations ADD CONSTRAINT integrations_company_id_provider_key UNIQUE (company_id, provider);
ALTER TABLE public.invitations ADD CONSTRAINT invitations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'revoked'::text, 'expired'::text])));
ALTER TABLE public.invitations ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);
ALTER TABLE public.invitations ADD CONSTRAINT invitations_token_key UNIQUE (token);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_folders ADD CONSTRAINT lead_folders_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_gen_results ADD CONSTRAINT lead_gen_results_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_gen_saved_searches ADD CONSTRAINT lead_gen_saved_searches_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_gen_sessions ADD CONSTRAINT lead_gen_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_icp_scores ADD CONSTRAINT lead_icp_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_icp_scores ADD CONSTRAINT lead_icp_scores_lead_id_icp_profile_id_key UNIQUE (lead_id, icp_profile_id);
ALTER TABLE public.leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.mcp_tokens ADD CONSTRAINT mcp_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.mcp_tokens ADD CONSTRAINT mcp_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE public.messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
ALTER TABLE public.meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_pkey PRIMARY KEY (id);
ALTER TABLE public.meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_company_id_account_id_key UNIQUE (company_id, account_id);
ALTER TABLE public.meta_connections ADD CONSTRAINT meta_connections_pkey PRIMARY KEY (id);
ALTER TABLE public.meta_connections ADD CONSTRAINT meta_connections_company_id_key UNIQUE (company_id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.openai_accounts ADD CONSTRAINT openai_accounts_pkey PRIMARY KEY (id);
ALTER TABLE public.openai_accounts ADD CONSTRAINT openai_accounts_company_id_key UNIQUE (company_id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.payroll ADD CONSTRAINT payroll_pkey PRIMARY KEY (id);
ALTER TABLE public.phone_provisions ADD CONSTRAINT phone_provisions_pkey PRIMARY KEY (id);
ALTER TABLE public.pipeline_stages ADD CONSTRAINT pipeline_stages_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.quotes ADD CONSTRAINT quotes_pkey PRIMARY KEY (id);
ALTER TABLE public.recruitment ADD CONSTRAINT recruitment_pkey PRIMARY KEY (id);
ALTER TABLE public.saved_lead_filters ADD CONSTRAINT saved_lead_filters_pkey PRIMARY KEY (id);
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_company_id_key UNIQUE (company_id);
ALTER TABLE public.suppressed_emails ADD CONSTRAINT suppressed_emails_reason_check CHECK ((reason = ANY (ARRAY['unsubscribe'::text, 'bounce'::text, 'complaint'::text])));
ALTER TABLE public.suppressed_emails ADD CONSTRAINT suppressed_emails_pkey PRIMARY KEY (id);
ALTER TABLE public.suppressed_emails ADD CONSTRAINT suppressed_emails_email_key UNIQUE (email);
ALTER TABLE public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE public.twilio_accounts ADD CONSTRAINT twilio_accounts_pkey PRIMARY KEY (id);
ALTER TABLE public.twilio_accounts ADD CONSTRAINT twilio_accounts_company_id_key UNIQUE (company_id);
ALTER TABLE public.usage_quotas ADD CONSTRAINT usage_quotas_pkey PRIMARY KEY (id);
ALTER TABLE public.usage_quotas ADD CONSTRAINT usage_quotas_company_id_quota_type_period_start_key UNIQUE (company_id, quota_type, period_start);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_agents ADD CONSTRAINT voice_agents_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_call_events ADD CONSTRAINT voice_call_events_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_calls ADD CONSTRAINT voice_calls_pkey PRIMARY KEY (id);
ALTER TABLE public.webhook_logs ADD CONSTRAINT webhook_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_pkey PRIMARY KEY (id);
ALTER TABLE public.work_schedules ADD CONSTRAINT work_schedules_pkey PRIMARY KEY (id);
ALTER TABLE public.workflows ADD CONSTRAINT workflows_pkey PRIMARY KEY (id);
ALTER TABLE public.workforce_settings ADD CONSTRAINT workforce_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.workforce_settings ADD CONSTRAINT workforce_settings_company_id_key UNIQUE (company_id);
ALTER TABLE public.workspace_events ADD CONSTRAINT workspace_events_pkey PRIMARY KEY (id);