-- Baseline: indexes
-- Consolidated from schema-recon reconstruction, verified applied against vbxlpxhvojlaisxcipyh

CREATE INDEX idx_activity_logs_company ON public.activity_logs USING btree (company_id, created_at DESC);
CREATE INDEX idx_activity_logs_company_created ON public.activity_logs USING btree (company_id, created_at DESC);
CREATE INDEX idx_activity_logs_created ON public.activity_logs USING btree (created_at DESC);
CREATE INDEX idx_activity_logs_user ON public.activity_logs USING btree (user_id, created_at DESC);
CREATE INDEX idx_ai_gen_company ON public.ai_generations USING btree (company_id, created_at DESC);
CREATE INDEX idx_ai_gen_status ON public.ai_generations USING btree (status);
CREATE INDEX idx_ai_gen_user ON public.ai_generations USING btree (user_id, created_at DESC);
CREATE INDEX idx_attendance_date ON public.attendance_logs USING btree (check_in);
CREATE INDEX idx_attendance_employee ON public.attendance_logs USING btree (employee_profile_id);
CREATE INDEX idx_attendance_logs_employee_date ON public.attendance_logs USING btree (employee_profile_id, check_in);
CREATE INDEX idx_autopilot_actions_company_status ON public.autopilot_actions USING btree (company_id, status);
CREATE INDEX idx_autopilot_actions_created ON public.autopilot_actions USING btree (created_at DESC);
CREATE INDEX idx_bulk_email_campaigns_company ON public.bulk_email_campaigns USING btree (company_id);
CREATE INDEX idx_bulk_email_recipients_campaign ON public.bulk_email_recipients USING btree (campaign_id);
CREATE INDEX idx_bulk_email_recipients_email ON public.bulk_email_recipients USING btree (email);
CREATE INDEX idx_calendar_company ON public.calendar_events USING btree (company_id);
CREATE INDEX idx_calendar_employee ON public.calendar_events USING btree (employee_profile_id);
CREATE INDEX idx_calendar_events_company_start ON public.calendar_events USING btree (company_id, start_time);
CREATE INDEX idx_calendar_time ON public.calendar_events USING btree (start_time, end_time);
CREATE INDEX idx_contact_submissions_created ON public.contact_submissions USING btree (created_at DESC);
CREATE INDEX idx_contact_submissions_email_created ON public.contact_submissions USING btree (lower(email), created_at DESC);
CREATE INDEX idx_customers_company_id ON public.customers USING btree (company_id);
CREATE INDEX idx_cvr_companies_city ON public.cvr_companies USING btree (company_id, city);
CREATE INDEX idx_cvr_companies_industry ON public.cvr_companies USING btree (company_id, industry);
CREATE INDEX idx_cvr_companies_status ON public.cvr_companies USING btree (company_id, cvr_status);
CREATE UNIQUE INDEX idx_cvr_companies_unique ON public.cvr_companies USING btree (company_id, cvr);
CREATE INDEX idx_deals_company_id ON public.deals USING btree (company_id);
CREATE INDEX idx_deals_company_stage ON public.deals USING btree (company_id, stage);
CREATE INDEX idx_deals_stage ON public.deals USING btree (stage);
CREATE INDEX idx_email_send_log_created ON public.email_send_log USING btree (created_at DESC);
CREATE INDEX idx_email_send_log_message ON public.email_send_log USING btree (message_id);
CREATE UNIQUE INDEX idx_email_send_log_message_sent_unique ON public.email_send_log USING btree (message_id) WHERE (status = 'sent'::text);
CREATE INDEX idx_email_send_log_recipient ON public.email_send_log USING btree (recipient_email);
CREATE INDEX idx_unsubscribe_tokens_token ON public.email_unsubscribe_tokens USING btree (token);
CREATE INDEX idx_emails_company_user ON public.emails USING btree (company_id, user_id);
CREATE INDEX idx_emails_received_at ON public.emails USING btree (received_at DESC);
CREATE INDEX idx_employee_profiles_company ON public.employee_profiles USING btree (company_id);
CREATE UNIQUE INDEX idx_employee_profiles_employee_id ON public.employee_profiles USING btree (employee_id);
CREATE INDEX idx_icp_profiles_company ON public.icp_profiles USING btree (company_id);
CREATE INDEX idx_icp_profiles_status ON public.icp_profiles USING btree (company_id, status);
CREATE INDEX idx_icp_search_jobs_company ON public.icp_search_jobs USING btree (company_id);
CREATE INDEX idx_icp_search_jobs_icp ON public.icp_search_jobs USING btree (icp_profile_id);
CREATE INDEX idx_integrations_company ON public.integrations USING btree (company_id);
CREATE INDEX idx_invitations_company_id ON public.invitations USING btree (company_id);
CREATE INDEX idx_invitations_email ON public.invitations USING btree (email);
CREATE INDEX idx_invitations_token ON public.invitations USING btree (token);
CREATE INDEX idx_invoices_company_id ON public.invoices USING btree (company_id);
CREATE INDEX idx_invoices_company_status ON public.invoices USING btree (company_id, status);
CREATE INDEX idx_invoices_status ON public.invoices USING btree (status);
CREATE INDEX idx_lead_folders_company ON public.lead_folders USING btree (company_id);
CREATE INDEX idx_lead_gen_results_company ON public.lead_gen_results USING btree (company_id);
CREATE INDEX idx_lead_gen_results_session ON public.lead_gen_results USING btree (session_id);
CREATE INDEX idx_lead_gen_saved_company ON public.lead_gen_saved_searches USING btree (company_id);
CREATE INDEX idx_lead_gen_sessions_company ON public.lead_gen_sessions USING btree (company_id);
CREATE INDEX idx_lead_gen_sessions_status ON public.lead_gen_sessions USING btree (status);
CREATE INDEX idx_lead_icp_scores_company ON public.lead_icp_scores USING btree (company_id);
CREATE INDEX idx_lead_icp_scores_icp ON public.lead_icp_scores USING btree (icp_profile_id);
CREATE INDEX idx_lead_icp_scores_lead ON public.lead_icp_scores USING btree (lead_id);
CREATE INDEX idx_lead_icp_scores_total ON public.lead_icp_scores USING btree (company_id, total_score DESC);
CREATE INDEX idx_leads_company_created ON public.leads USING btree (company_id, created_at DESC);
CREATE INDEX idx_leads_company_id ON public.leads USING btree (company_id);
CREATE INDEX idx_leads_company_stage ON public.leads USING btree (company_id, status);
CREATE INDEX idx_leads_company_status ON public.leads USING btree (company_id, status);
CREATE INDEX idx_leads_folder ON public.leads USING btree (folder_id);
CREATE INDEX idx_leads_import_batch ON public.leads USING btree (import_batch_id);
CREATE INDEX idx_leads_last_touched ON public.leads USING btree (last_touched_at);
CREATE INDEX idx_leads_next_followup ON public.leads USING btree (next_followup_at);
CREATE INDEX idx_leads_owner ON public.leads USING btree (owner_id);
CREATE INDEX idx_leads_status ON public.leads USING btree (status);
CREATE INDEX idx_leave_requests_company_id ON public.leave_requests USING btree (company_id);
CREATE INDEX idx_mcp_tokens_company ON public.mcp_tokens USING btree (company_id);
CREATE INDEX idx_mcp_tokens_hash ON public.mcp_tokens USING btree (token_hash) WHERE (revoked_at IS NULL);
CREATE INDEX idx_messages_company_id ON public.messages USING btree (company_id);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX idx_notifications_user_read ON public.notifications USING btree (user_id, read);
CREATE INDEX idx_payments_company_id ON public.payments USING btree (company_id);
CREATE INDEX idx_payroll_company_id ON public.payroll USING btree (company_id);
CREATE INDEX idx_profiles_user_company ON public.profiles USING btree (user_id, company_id);
CREATE INDEX idx_recruitment_company_id ON public.recruitment USING btree (company_id);
CREATE INDEX idx_suppressed_emails_email ON public.suppressed_emails USING btree (email);
CREATE INDEX idx_tasks_assigned_to ON public.tasks USING btree (assigned_to);
CREATE INDEX idx_tasks_company_id ON public.tasks USING btree (company_id);
CREATE INDEX idx_tasks_company_status ON public.tasks USING btree (company_id, status);
CREATE INDEX idx_user_roles_user_role ON public.user_roles USING btree (user_id, role);
CREATE INDEX idx_user_sessions_ended_at ON public.user_sessions USING btree (ended_at) WHERE (ended_at IS NOT NULL);
CREATE INDEX idx_voice_agents_company ON public.voice_agents USING btree (company_id);
CREATE INDEX idx_voice_call_events_call ON public.voice_call_events USING btree (call_id, timestamp_ms);
CREATE INDEX idx_voice_calls_company ON public.voice_calls USING btree (company_id);
CREATE INDEX idx_voice_calls_sid ON public.voice_calls USING btree (twilio_call_sid);
CREATE INDEX idx_voice_calls_started ON public.voice_calls USING btree (started_at DESC);
CREATE INDEX idx_webhook_logs_company ON public.webhook_logs USING btree (company_id, created_at DESC);
CREATE INDEX idx_webhook_logs_webhook ON public.webhook_logs USING btree (webhook_id, created_at DESC);
CREATE INDEX idx_webhooks_active ON public.webhooks USING btree (company_id, is_active);
CREATE INDEX idx_webhooks_company_event ON public.webhooks USING btree (company_id, event);
CREATE INDEX idx_work_schedules_company_date ON public.work_schedules USING btree (company_id, schedule_date);
CREATE INDEX idx_work_schedules_employee ON public.work_schedules USING btree (employee_profile_id, schedule_date);
CREATE INDEX idx_we_company_time ON public.workspace_events USING btree (company_id, created_at DESC);
CREATE INDEX idx_we_type ON public.workspace_events USING btree (company_id, type, created_at DESC);