-- Baseline: foreign key constraints
-- Consolidated from schema-recon reconstruction, verified applied against vbxlpxhvojlaisxcipyh

ALTER TABLE public.activity_logs ADD CONSTRAINT activity_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.ai_generations ADD CONSTRAINT ai_generations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.attendance_logs ADD CONSTRAINT attendance_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.attendance_logs ADD CONSTRAINT attendance_logs_employee_profile_id_fkey FOREIGN KEY (employee_profile_id) REFERENCES employee_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.autopilot_actions ADD CONSTRAINT autopilot_actions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.autopilot_actions ADD CONSTRAINT autopilot_actions_triggered_by_event_fkey FOREIGN KEY (triggered_by_event) REFERENCES workspace_events(id) ON DELETE SET NULL;
ALTER TABLE public.bulk_email_campaigns ADD CONSTRAINT bulk_email_campaigns_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.bulk_email_recipients ADD CONSTRAINT bulk_email_recipients_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.bulk_email_recipients ADD CONSTRAINT bulk_email_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES bulk_email_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_employee_profile_id_fkey FOREIGN KEY (employee_profile_id) REFERENCES employee_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.cold_caller_usage ADD CONSTRAINT cold_caller_usage_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.consent_logs ADD CONSTRAINT consent_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.customers ADD CONSTRAINT customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.cvr_companies ADD CONSTRAINT cvr_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.deals ADD CONSTRAINT deals_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.deals ADD CONSTRAINT deals_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.deals ADD CONSTRAINT deals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(user_id);
ALTER TABLE public.email_accounts ADD CONSTRAINT email_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.emails ADD CONSTRAINT emails_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.emails ADD CONSTRAINT emails_email_account_id_fkey FOREIGN KEY (email_account_id) REFERENCES email_accounts(id) ON DELETE CASCADE;
ALTER TABLE public.employee_profiles ADD CONSTRAINT employee_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.employee_profiles ADD CONSTRAINT employee_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.employee_profiles ADD CONSTRAINT employee_profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.event_subscriptions ADD CONSTRAINT event_subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.icp_profiles ADD CONSTRAINT icp_profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.icp_search_jobs ADD CONSTRAINT icp_search_jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.icp_search_jobs ADD CONSTRAINT icp_search_jobs_icp_profile_id_fkey FOREIGN KEY (icp_profile_id) REFERENCES icp_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.invitations ADD CONSTRAINT invitations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.lead_folders ADD CONSTRAINT lead_folders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.lead_gen_results ADD CONSTRAINT lead_gen_results_session_id_fkey FOREIGN KEY (session_id) REFERENCES lead_gen_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.lead_gen_results ADD CONSTRAINT lead_gen_results_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.lead_gen_saved_searches ADD CONSTRAINT lead_gen_saved_searches_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.lead_gen_sessions ADD CONSTRAINT lead_gen_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.lead_icp_scores ADD CONSTRAINT lead_icp_scores_icp_profile_id_fkey FOREIGN KEY (icp_profile_id) REFERENCES icp_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.lead_icp_scores ADD CONSTRAINT lead_icp_scores_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.lead_icp_scores ADD CONSTRAINT lead_icp_scores_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE public.leads ADD CONSTRAINT leads_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(user_id);
ALTER TABLE public.leads ADD CONSTRAINT leads_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.leads ADD CONSTRAINT leads_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES lead_folders(id) ON DELETE SET NULL;
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_employee_profile_id_fkey FOREIGN KEY (employee_profile_id) REFERENCES employee_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.mcp_tokens ADD CONSTRAINT mcp_tokens_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.messages ADD CONSTRAINT messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_meta_connection_id_fkey FOREIGN KEY (meta_connection_id) REFERENCES meta_connections(id) ON DELETE CASCADE;
ALTER TABLE public.meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.meta_connections ADD CONSTRAINT meta_connections_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.openai_accounts ADD CONSTRAINT openai_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
ALTER TABLE public.payroll ADD CONSTRAINT payroll_employee_profile_id_fkey FOREIGN KEY (employee_profile_id) REFERENCES employee_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.payroll ADD CONSTRAINT payroll_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.phone_provisions ADD CONSTRAINT phone_provisions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_stages ADD CONSTRAINT pipeline_stages_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
ALTER TABLE public.recruitment ADD CONSTRAINT recruitment_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.saved_lead_filters ADD CONSTRAINT saved_lead_filters_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(user_id);
ALTER TABLE public.tasks ADD CONSTRAINT tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
ALTER TABLE public.teams ADD CONSTRAINT teams_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.twilio_accounts ADD CONSTRAINT twilio_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.usage_quotas ADD CONSTRAINT usage_quotas_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.voice_agents ADD CONSTRAINT voice_agents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.voice_call_events ADD CONSTRAINT voice_call_events_call_id_fkey FOREIGN KEY (call_id) REFERENCES voice_calls(id) ON DELETE CASCADE;
ALTER TABLE public.voice_call_events ADD CONSTRAINT voice_call_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.voice_calls ADD CONSTRAINT voice_calls_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.voice_calls ADD CONSTRAINT voice_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES voice_agents(id) ON DELETE SET NULL;
ALTER TABLE public.webhook_logs ADD CONSTRAINT webhook_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.webhook_logs ADD CONSTRAINT webhook_logs_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE;
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.work_schedules ADD CONSTRAINT work_schedules_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.work_schedules ADD CONSTRAINT work_schedules_employee_profile_id_fkey FOREIGN KEY (employee_profile_id) REFERENCES employee_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.workflows ADD CONSTRAINT workflows_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.workforce_settings ADD CONSTRAINT workforce_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.workspace_events ADD CONSTRAINT workspace_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;